export const enCustomLocale = {
  monthNames: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  monthNamesShort: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  dayNames: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  today: "Today",
  // You can also set formats for the agenda view if your calendar component supports it
  agendaDateFormat: "MMMM dd, yyyy",
  agendaMonthFormat: "MMMM yyyy",
  agendaDayFormat: "dddd",
  agendaDayNumFormat: "dd",
  firstDay: 1, // Start the week on Sunday
};

export const jaCustomLocale = {
  monthNames: [
    "1月",
    "2月",
    "3月",
    "4月",
    "5月",
    "6月",
    "7月",
    "8月",
    "9月",
    "10月",
    "11月",
    "12月",
  ],
  monthNamesShort: [
    "1月",
    "2月",
    "3月",
    "4月",
    "5月",
    "6月",
    "7月",
    "8月",
    "9月",
    "10月",
    "11月",
    "12月",
  ],
  dayNames: [
    "日曜日",
    "月曜日",
    "火曜日",
    "水曜日",
    "木曜日",
    "金曜日",
    "土曜日",
  ],
  dayNamesShort: ["日", "月", "火", "水", "木", "金", "土"],
  today: "今日",
  // You can also set formats for the agenda view if your calendar component supports it
  agendaDateFormat: "yyyy年MM月dd日",
  agendaMonthFormat: "yyyy年MM月",
  agendaDayFormat: "yyyy年MM月dd日",
  agendaDayNumFormat: "dd",
  firstDay: 1, // Start the week on Sunday
};
